version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --no-beefy
      - --force-authoring
    environment:
      RUST_LOG: debug
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --no-beefy
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-charlie:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - relaychain-charlie:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=charlie
      - --charlie
      - --rpc-methods=unsafe
      - --no-beefy
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  parachain-2000-0:
    ports:
      - 9947:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - parachain-2000-0:/acala/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --base-path=/acala/data
      - --chain=/app/karura-latest-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --parachain-id=2000
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=c1ca909c33837e48411e32f1b73b02f63ecffe1abeaf0f68d1a2112b8778d369
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --no-beefy
      - --name=relaychain-alice
    environment:
      RUST_LOG: debug
    ulimits: *a1
  parachain-2000-1:
    ports:
      - 9948:9944
      - 9937:9933
      - 30337:30333
    volumes:
      - parachain-2000-1:/acala/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --base-path=/acala/data
      - --chain=/app/karura-latest-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-1
      - --collator
      - --parachain-id=2000
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --bob
      - --bootnodes=/dns/parachain-2000-0/tcp/30333/p2p/12D3KooWFnxXjTND1pYdGxq1dBMBuNPykCtYW34vC1VtSpDfo72U
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --no-beefy
    environment:
      RUST_LOG: sc_basic_authorship=trace
    ulimits: *a1
  parachain-2000-2:
    ports:
      - 9949:9944
      - 9938:9933
      - 30338:30333
    volumes:
      - parachain-2000-2:/acala/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --base-path=/acala/data
      - --chain=/app/karura-latest-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-2
      - --collator
      - --parachain-id=2000
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --charlie
      - --bootnodes=/dns/parachain-2000-0/tcp/30333/p2p/12D3KooWFnxXjTND1pYdGxq1dBMBuNPykCtYW34vC1VtSpDfo72U
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --no-beefy
    environment:
      RUST_LOG: sc_basic_authorship=trace
    ulimits: *a1
volumes:
  ? relaychain-alice
  ? relaychain-bob
  ? relaychain-charlie
  ? parachain-2000-0
  ? parachain-2000-1
  ? parachain-2000-2
