[package]
name = "nftmart-contract"
version = "0.1.0"
authors = ["nftmart"]
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false }
ink_lang = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { version = "3.0.0-rc3",git = "https://github.com/paritytech/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }

contract-types = { git = "https://github.com/NFTT-studio/nftmart-node.git", branch = "dev", default-features = false}

[lib]
name = "nftmart_contract"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
    "ink_prelude/std",
    "contract-types/std",
]
ink-as-dependency = []
